---
- name: Quick Demo Playbook for AWS Linux EC2
  hosts: all
  become: yes

  tasks:
    - name: add Ansible user
      user:
        name: ansible
        state: present
      tags:
        - user

    - name: Create a text file in home dir
      copy:
        content: "This server is managed by Ansible. Hello from Terraform!"
        dest: /home/ec2-user/welcome.txt
        owner: ec2-user
        group: ec2-user
        mode: '0644'
      tags:
        - file
